---
title: "Untitled"
output: html_document
date: "2023-08-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Mortality from content.sph.harvard.edu/xlin/
```{r}
# download January 22, 2022, at 07.30 am, from here: global data https://github.com/lin-lab/COVID19-Rt/blob/master/initial_estimates/README.md
#https://content.sph.harvard.edu/xlin/
#death: accumulated 
#deathIncrease: number of death increase by each day

# Other source from https://ourworldindata.org/coronavirus-source-data
#https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv

# Follow Johns Hopkins: calculate death per 100K population 
# https://coronavirus.jhu.edu/data/mortality

#why NOT partition in pandemic waves? because there's no clear cut point:
#https://www.yalemedicine.org/news/covid-19-variants-of-concern-omicron
death_outcome <- rio::import(here::here("data", "jhu_global_rt_downloadedjan22_2022.tsv")) %>% 
  select(date, Country_Region, death, deathIncrease, iso2, iso3, population) %>% 
  filter(date <= "2021-12-31") %>% 
  
  # normalize death number
  mutate(death_100Kpop = round((death/population)*100000, 2), 
         death_insrease_day_100Kpop = round((deathIncrease/population)*100000, 2)) %>% 
  
  # adding timepoint  - month
  mutate(date = as.POSIXct(date), 
         month = month(date),
         year = year(date),
         time_month = case_when(year == 2020 ~ month,
                                year == 2021 & month == 1 ~ 13, 
                                year == 2021 & month == 2 ~ 14,
                                year == 2021 & month == 3 ~ 15,
                                year == 2021 & month == 4 ~ 16,
                                year == 2021 & month == 5 ~ 17,
                                year == 2021 & month == 6 ~ 18,
                                year == 2021 & month == 7 ~ 19,
                                year == 2021 & month == 8 ~ 20,
                                year == 2021 & month == 9 ~ 21,
                                year == 2021 & month == 10 ~ 22,
                                year == 2021 & month == 11 ~ 23,
                                year == 2021 & month == 12 ~ 24)) %>% 
  mutate(time_month = time_month - 3) %>% # center month 0 at the beginning of data set

     # adding timepoint  - quarter     
  mutate(quarter = quarter(date, with_year = TRUE),
      # approach 1 to count quarter: collapse March 2020 into second quarter
   quarter = ifelse(quarter == "2020.1", "2020.2", quarter)) %>% 
  
  # approach 2 to count quarter: exclude March 2020, starting time point from April 2020 
   # filter(quarter != "2020.1") %>% 
    mutate(time_quarter = case_when( quarter == "2020.2"  ~ 0, 
                             quarter == "2020.3" ~ 1,
                             quarter == "2020.4" ~ 2,
                             quarter == "2021.1" ~ 3,
                             quarter == "2021.2" ~ 4,
                             quarter == "2021.3" ~ 5,
                             quarter == "2021.4" ~ 6)) %>% 

   # compute outcome: mean death each quarter by country
  group_by(iso3, time_month) %>% 
  mutate(death_mean_quarter = mean(death_100Kpop, na.rm = TRUE)) 



```


# Joining data - Outcome from Havard Chan
```{r joining data}
data <- death_outcome %>% #distinct(Country_Region) %>% count() # 196
    left_join(gdp_percap) %>% 
    left_join(gov_effectiveness_corruption) %>% 
    left_join(democracy) %>% 
    left_join(health_index, by = c("name" = "Country")) %>% 
    left_join(trust) %>% 
    left_join(fsi2019) %>% 
 
    select(-c(Country_Region, `Country Name`, iso2)) %>% 
  
# coding unitary_federal - Method 1
    mutate(unitary_federal= case_when(name %in% federal ~ 1,
                                      !name %in% federal ~ 0)) %>%

# coding unitary_federal - Method 2
    mutate(unitary_semi_federal= case_when(name %in% non_unitary ~ 1, 
                                      !name %in% non_unitary ~ 0)) %>%   

# limit to only some variables to be used in model
  select(name, time, death_mean_quarter, gdp_percap, gov_eff, democracy, 
         health_index, unitary_federal, unitary_semi_federal, trust_gov) %>% 
  drop_na(name) %>% 
  distinct()


summary(data)
  
saveRDS(data, "data.RDS")


```


## Random quadratic term
Let the quadratic component (time square term) vary by country, main effect of government effectiveness show significant negative effect on Covid death.  

```{r}
# m_join7 <- lmer(total_deaths_per_million ~ time_month + I(time_month^2) + (I(time_month^2)|name)  + log(gdp_percap) + health_index +  
#             unitary_semi_federal +
#             I(time_month^2)*scale(democracy) +
#             I(time_month^2)*scale(gov_eff),
#           data = data_owid, 
#           control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))
# summary(m_join7)

```
